
version: '2'

services:
  nodetestlinux:
    image: nodetestlinux:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 1337:1337
      - 5858:5858
    volumes:
      - .:/usr/src/app
    command: node --debug=5858 server.js
